### ISSUE TITLE
[feature request] line breaks

### ISSUE THREAD

**Issue by SdlasHeras** [DigitalCloud/laravel-model-notes#2]
I like this package but I have some difficulties when I add for example a note to a user with bank details, I usually separate these details with line breaks but I can't do that since when I hit enter it submits the note.

Thanks for your work!

**Comment by devmtm** [comment]
You can press shift+enter to prevent note submit.

**Comment by SdlasHeras** [comment]
Hi, sorry I think that the problem is in the nova-resource-notes package. Tried with Mac 10.14.4, Chrome 73.0.3683.103 and it submits the note using shift + enter.
